(defun EstDans (labyrinthe I J)
  (if (equal I 0)
      (setq CurrentList (car labyrinthe))
  )
  (if (equal I 1)
      (setq CurrentList (car(cdr labyrinthe)))
      )
  (if (equal I 2)(setq CurrentList (car(cdr(cdr labyrinthe)))))
  (if (equal I 3)(setq CurrentList (car(cdr(cdr(cdr labyrinthe))))))
  (if (equal I 4)(setq CurrentList (car(cdr(cdr(cdr(cdr labyrinthe)))))))
  (if (equal I 5)(setq CurrentList (car(cdr(cdr(cdr(cdr(cdr labyrinthe))))))))
  (if (equal I 6)(setq CurrentList (car(cdr(cdr(cdr(cdr(cdr(cdr labyrinthe)))))))))
  (if (equal I 7)(setq CurrentList (car(cdr(cdr(cdr(cdr(cdr(cdr(cdr labyrinthe))))))))))

  (if (and (equal J 0))(setq CurrentAtom (car CurrentList)))
  (if (and (equal J 1))(setq CurrentAtom (car(cdr CurrentList))))
  (if (and (equal J 2))(setq CurrentAtom (car(cdr(cdr CurrentList)))))
  (if (and (equal J 3))(setq CurrentAtom (car(cdr(cdr(cdr CurrentList))))))
  (if (and (equal J 4))(setq CurrentAtom (car(cdr(cdr(cdr(cdr CurrentList)))))))
  (if (and (equal J 5))(setq CurrentAtom (car(cdr(cdr(cdr(cdr(cdr CurrentList))))))))
  (if (and (equal J 6))(setq CurrentAtom (car(cdr(cdr(cdr(cdr(cdr(cdr CurrentList)))))))))
  (if (and (equal J 7))(setq CurrentAtom (car(cdr(cdr(cdr(cdr(cdr(cdr(cdr CurrentList))))))))))
  (if (and (equal J 8))(setq CurrentAtom (car(cdr(cdr(cdr(cdr(cdr(cdr(cdr(cdr CurrentList)))))))))))
  (if (and (equal J 9))(setq CurrentAtom (car(cdr(cdr(cdr(cdr(cdr(cdr(cdr(cdr(cdr CurrentList))))))))))))
  (if (and (equal J 10))(setq CurrentAtom (car(cdr(cdr(cdr(cdr(cdr(cdr(cdr(cdr(cdr(cdr CurrentList)))))))))))))
  (if (and (equal J 11))(setq CurrentAtom (car(cdr(cdr(cdr(cdr(cdr(cdr(cdr(cdr(cdr(cdr(cdr CurrentList))))))))))))))

  (return CurrentAtom)
)
